providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "nodejs_22_12"]

[phases.install]
cmds = [
	"node -v",
	"python3 -m venv /app/.venv",
	"/app/.venv/bin/pip install --upgrade pip",
	"/app/.venv/bin/pip install -r requirements.txt",
	"cd frontend && npm install"
]

[phases.build]
cmds = [
	"cd frontend && npm run build"
]

[start]
cmd = "/app/.venv/bin/gunicorn run:app"
